### ISSUE TITLE
Solamente se permite el acceso a usuarios con cuentas válidas.

### ISSUE THREAD

**Issue by Raquel-95** [Raquel-95/LIM014-social-network#1]

**Comment by Giulianayarleque** [comment]
- [ ] Realizar maquetación con HTML la pagina de Login.
- [ ] Revisar objetivo de aprendizaje - Firebase.
- [ ] Autenticación con correo electrónico y contraseña.
- [ ] Aplicar metodo createUserWithEmailAndPassword( )

**Comment by Giulianayarleque** [comment]
- [ ] Realizar maquetación con HTML la pagina de Login.
- [ ] Autenticación con correo electrónico y contraseña.
- [ ] Aplicar metodo createUserWithEmailAndPassword( )
